### ISSUE TITLE
"Cannot set Expression. It is marked as 'NonShareable' and has already been used" wehn setting format to SelectedDate of DatePicker WPF control

### ISSUE THREAD

**Issue by saritsegal** [snoopwpf/snoopwpf#50] opened 2016-06-07 15:18 UTC

**Comment by batzen** [comment] 2019-09-28 12:49
Would need more details on this one. A sample app showcasing/reproducing the issue would be nice.
Due to the age of this issue i will close it. If you have more details feel free to re-open this issue.

**Closed by batzen** 2019-09-28 12:49 UTC
