### ISSUE TITLE
Cannot find WPF element in .NET 4.5.1 ElementHost

### ISSUE THREAD

**Issue by krk** [snoopwpf/snoopwpf#15] opened 2013-10-25 08:28 UTC
Cannot find WPF element in .NET 4.5.1 ElementHost

**Comment by batzen** [comment] 2019-09-28 12:44
Would need more details on this one. A sample app showcasing/reproducing the issue would be nice.
Due to the age of this issue i will close it. If you have more details feel free to re-open this issue.

**Closed by batzen** 2019-09-28 12:44 UTC
