### ISSUE TITLE
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.

### ISSUE THREAD

**Issue by perlun** [snoopwpf/snoopwpf#66] opened 2018-03-06 12:30 UTC
When the WPF application I was attached to reloaded its data (and the visual tree likely was refreshed as well), Snoop triggered an exception that crashed the whole WPF app. Here is the stack trace:

```
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Collections.Generic.List`1.Enumerator.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Snoop.Shell.VisualTreeProviderExtensions.NodeName(VisualTreeItem item)
   at Snoop.Shell.VisualTreeProvider.GetTreeItem(String path)
   at Snoop.Shell.VisualTreeProvider.OnSyncSelectedItem(Object _)
   at System.Threading.TimerQueueTimer.CallCallbackInContext(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.TimerQueue.FireNextTimers()
   at System.Threading.TimerQueue.AppDomainTimerCallback()
```

**Comment by cplotts** [comment] 2018-08-02 20:10
@perlun this seems to be an issue in the application that you were Snooping (and not with Snoop itself).

Since Snoop actually injects itself into the Snooped process, exceptions that happen there might seem to come from Snoop ... when they do not.

Unless you can provide some sample code that illustrates otherwise ... I am going to close this issue.

**Comment by perlun** [comment] 2018-08-03 11:00
@cplotts Thanks. No longer working actively on that project, so we can safely close this for now unless we find a way to reproduce it.

Can application-generated exceptions be re-thrown from the `Snoop.Shell.VisualTreeProvider.OnSyncSelectedItem` method?

**Comment by batzen** [comment] 2018-08-03 11:17
To be honest, i think this is a bug in snoop itself.

We are using linq here which evaluates lazy and we are using a timer to refresh things.
If the evaluation/refresh take longer than the timer interval, which currently is 250ms, we modify the list we are currently working on.
The problem is that there is no guard against re-entrancy etc..

While debugging i noticed that the powershell integration adds quite some overhead, like this timer and everything it does on tick, even if you don't use the powershell tab at all.

**Comment by cplotts** [comment] 2018-08-07 13:49
I'll reopen this ... I honestly didn't look close enough. @batzen I think you are right.

I wonder if we could limit the impact of the PowerShell tab by only starting this timer when the tab is active.

**Closed** 2019-12-26 12:23 UTC
Labels: bug
