### ISSUE TITLE
Target button no longer working under Windows 10 1903

### ISSUE THREAD

**Issue by moonkey124** [snoopwpf/snoopwpf#128] opened 2019-05-27 09:59 UTC
After updating to the spring release in 2019 the newest snoop version is no longer working. When trying to drag on drop the target on to a wpf application nothing happens. 

It works however when you select the application in the list view.

**Comment by batzen** [comment] 2019-05-27 14:09
Will have a look during the weekend. At least i hope so.

**Comment by batzen** [comment] 2019-05-27 17:07
Just tested this on my machine and it works as expected...
Which version of snoop are you using?

**Comment by moonkey124** [comment] 2019-05-27 17:28
So I tested it again on my personal computer at home and it worked flawlessly. However when I was at work it didn't and several coworkers had the same problem. I do not have to most up to date version of our software at home so I have to test it again once I am back at work. Unfortunately this won't be until next monday. We are using Snoop 2.10. Next Monday I will try to figure out whats the problem. I will keep you posted

**Comment by jusovsky** [comment] 2019-05-28 16:23
I'm experiencing the same problem with the target button in Snoop 2.1 after updating Windows to 1903.  I'm on VS 2019 version 16.1.1.  Behavior is the same when targeting multiple WPF applications, with and without the debugger attached, whether Snoop is run under the administrator context or current user.

**Comment by moonkey124** [comment] 2019-06-03 08:40
So I tried it on a new Windows 10 1903 VM and the same problem occurred with a simple .net 4.7.2 and 4.8 WPF app. 
After trying some stuff out I came across the following workaround attached as an image below. However this doesn't fix everything. For example when trying to use the target the snoop icon still doesn't appear. I hope this helps to create a  proper fix.
![SnoopWorkaround](https://user-images.githubusercontent.com/23150076/58788334-fbcf8200-85eb-11e9-8ca3-a0081202b620.png)

**Comment by batzen** [comment] 2019-06-05 19:39
So to clarify:
- The ComboBox shows your application and injecting from there works
- The window finder does not work when moved over your window, but if you remove the LeftButton condition it works again

Is that correct?

I don't understand what you mean with:

> For example when trying to use the target the snoop icon still doesn't appear. I hope this helps to create a proper fix.

**Comment by klausdost** [comment] 2019-06-06 04:55
See also https://github.com/microsoft/dotnet/issues/1026

**Comment by klausdost** [comment] 2019-06-06 05:01
> 
> 
> So to clarify:
> 
>     * The ComboBox shows your application and injecting from there works
> 
>     * The window finder does not work when moved over your window, but if you remove the LeftButton condition it works again
> 
> 
> Is that correct?
> 
> I don't understand what you mean with:
> 
> > For example when trying to use the target the snoop icon still doesn't appear.

At least this is a change that will allow to use the window finder with Windows 1903 / .Net 4.8. Also see my previous comment with a link to a similar issue, some strange things seem to happen with existing WPF applications when moving to .Net 4.8.

**Comment by fxxm** [comment] 2019-06-11 18:18
Ahh, it appears to be touch-screen related. 

On a hunch I disabled my HID-compliant touch screen (laptop has touch screen) and restarted snoop and the crosshairs work again.

**Comment by batzen** [comment] 2019-06-11 18:41
Then my attempt to fix it with https://github.com/snoopwpf/snoopwpf/commit/925b29360647f9da74b305937cf1b1df18412e50 might already be enough. Could you try that? I don't own a touch screen...

**Comment by fxxm** [comment] 2019-06-11 18:56
> Then my attempt to fix it with [925b293](https://github.com/snoopwpf/snoopwpf/commit/925b29360647f9da74b305937cf1b1df18412e50) might already be enough. Could you try that? I don't own a touch screen...

That doesn't work unfortunately. To be clear, the cursor never changes (i.e you don't get the mouse (?) picture with the app name) when you drag it over any window. Also, possibly related, the OnMouseLeftButtonUp doesn't seem to fire when you leave go of the mouse after dragging.

**Comment by batzen** [comment] 2019-06-11 21:20
I will try to add some tracing code and add a link to the CI build to allow people to download the latest preview versions. I hope to get that done during the weekend. Maybe we can find the issue that way.

**Comment by fxxm** [comment] 2019-06-12 05:55
I put in some debug code and it appears that OnMouseMove stops firing once the dragged mouse moves off of the Snoop window (if the touch-screen is enabled).

**Comment by matthew-a-thomas** [comment] 2019-06-27 17:47
> OnMouseMove stops firing once the dragged mouse moves off of the Snoop window

That would explain why resizing WPF windows has been funny lately... drag the window corner too fast and you begin selecting things behind the window. Very frustrating.

Anyway, I'm willing to help resolve this issue because I'm running into it, too. I've got a shovel. Someone just tell me where to dig.

**Comment by batzen** [comment] 2019-06-29 18:32
I might have found a workaround to this issue.
Would anyone be will to try a private built version of snoop from my machine?
I am not sure if it fixes the issue and i am not sure if it will work on all windows versions but it's worth a try i guess.
@moonkey124 @jusovsky @klausdost @matthew-a-thomas @fxxm

**Comment by moonkey124** [comment] 2019-06-29 18:34
Sounds great, I can test it right now

**Comment by batzen** [comment] 2019-06-29 18:35
Ok, just give me a second.

**Comment by batzen** [comment] 2019-06-29 18:40
[Snoop.2.11.0.0.zip](https://github.com/snoopwpf/snoopwpf/files/3342206/Snoop.2.11.0.0.zip)
There you go. It's just a test version to verify my approach. So expect the cursor to flicker.

**Comment by moonkey124** [comment] 2019-06-29 18:53
So I tried on a Microsoft Surface Book which has a touch display and simply nothing happend exactly like before. So I tried on another pc which has no touch display and every application instantly crashed. After that I tried it with a very simple wpf application and it showed the following exception as soon as I let loose of the target: "System.NotSupportedException: 'Es wurde versucht, eine Assembly von einer Netzwerkadresse zu laden, was in früheren Versionen von .NET Framework zum Ausführen der Assembly als Sandkastenassembly geführt hätte. In dieser Version von .NET Framework wird die CAS-Richtlinie standardmäßig nicht aktiviert, dieser Ladevorgang kann daher gefährlich sein. Wenn Sie nicht beabsichtigen, durch diesen Ladevorgang eine Sandkastenassembly zu erstellen, aktivieren Sie den loadFromRemoteSources-Schalter. Weitere Informationen finden Sie unter "http://go.microsoft.com/fwlink/?LinkId=155569".'"

**Comment by batzen** [comment] 2019-06-29 18:56
I guess you have to unblock the zip file after downloading it.
Otherwise windows will prevent the extracted application from launching.
You just have to open the properties (Eigenschaften) of the file set that that option before extracting.

But you don't have to try further as that solution didn't work on your surface.
Will try a different path then.

**Comment by moonkey124** [comment] 2019-06-29 18:57
Alright thanks in advance

**Comment by batzen** [comment] 2019-06-29 20:12
@moonkey124 I got another version for you. Would be nice if you could test that.
[Snoop.2.11.0.0_LowLevelMouse.zip](https://github.com/snoopwpf/snoopwpf/files/3342275/Snoop.2.11.0.0_LowLevelMouse.zip)

**Comment by fergus-azyra** [comment] 2019-06-29 20:19
> @moonkey124 I got another version for you. Would be nice if you could test that.
> [Snoop.2.11.0.0_LowLevelMouse.zip](https://github.com/snoopwpf/snoopwpf/files/3342275/Snoop.2.11.0.0_LowLevelMouse.zip)

Works like a charm! Well done!

**Comment by fxxm** [comment] 2019-06-29 20:23
> @moonkey124 I got another version for you. Would be nice if you could test that.
> [Snoop.2.11.0.0_LowLevelMouse.zip](https://github.com/snoopwpf/snoopwpf/files/3342275/Snoop.2.11.0.0_LowLevelMouse.zip)

That works perfectly for me! Thanks!

**Comment by batzen** [comment] 2019-06-29 20:39
Nice.
@matthew-a-thomas Could you also test this with the Snoop.2.11.0.0_LowLevelMouse.zip file?
When you also confirm that the issue is fixed i can release Snoop 2.11.

**Comment by moonkey124** [comment] 2019-06-29 21:23
Awesome! Can confirm that this version works perfectly, thanks a lot!

**Comment by batzen** [comment] 2019-06-29 21:57
You are welcome.
Now i learned (or had to learn) how to use low level mouse hooks and how to dynamically create mouse cursors.

**Closed** 2019-07-06 13:06 UTC
Labels: bug
