### ISSUE TITLE
The system cannot find the file specified

### ISSUE THREAD

**Issue by Antebellum110** [snoopwpf/snoopwpf#123] opened 2019-03-25 10:07 UTC
Falied to attach tp 'XXXXX' [12396]

Exception details:
System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Snoop.Injector.Launch(WindowInfo windowInfo, Assembly assembly, String className, String methodName, String settingsFile) in C:\Users\glubbe\Documents\Visual Studio 2017\Tools\Snoop\snoopwpf-master\Snoop\Injector.cs:line 35
   at Snoop.WindowInfo.Magnify() in C:\Users\glubbe\Documents\Visual Studio 2017\Tools\Snoop\snoopwpf-master\Snoop\WindowInfo.cs:line 215

---
### Environment
- Snoop 2.11.0.0
- Windows 6.3.15063
- .NET Framework 4.0.30319.42000

**Comment by batzen** [comment] 2019-03-25 17:27
I think this is a duplicate of https://github.com/cplotts/snoopwpf/issues/121
Have you used the Snoop.sln to build snoop or did you only use Snoop.csproj?

**Comment by batzen** [comment] 2019-04-16 16:14
@Antebellum110 ping

**Comment by batzen** [comment] 2019-06-29 18:13
Snoop 2.11 will contain details in the exception message.

**Closed by batzen** 2019-06-29 18:13 UTC
