### ISSUE TITLE
My Style is being applied to the "Change Target" Window

### ISSUE THREAD

**Issue by Nekeniehl** [snoopwpf/snoopwpf#101] opened 2018-11-14 10:58 UTC
Its not an important bug at all, but when I trigger the Change Target in the Method tab, my Scrollbar style is being applied.

![dermafc gui wpf_u8cywz9bjj](https://user-images.githubusercontent.com/3227198/48477361-b0958380-e801-11e8-81fb-228be53448a4.png)

I guess the problem is a missing `Style="{x:Null}"` in `PropertyGrid2.xaml` Control. Funny thing is that I have that style with a Key, not sure why is affecting.

**Comment by itsho** [comment] 2018-11-27 12:45
I think it's duplicate of #60 which is already solved. 
are you using the latest version?

**Comment by Nekeniehl** [comment] 2018-11-30 10:22
> 
> 
> I think it's duplicate of #60 which is already solved.
> are you using the latest version?

I am using 2.10.0.0, The latest available.

**Comment by batzen** [comment] 2019-04-16 16:20
@Nekeniehl Could you provide a small repro project for this? Even the whole app would be nice.

**Comment by knockatnight** [comment] 2019-04-23 12:32
Hey @batzen,

I wasn't sure I could reproduce it outside my project, but I could, I created a small WPF App with the same style. 

Attached you can find the complete solution.

Also a Screenshot

**Comment by batzen** [comment] 2019-04-25 16:04
Ok. Will have a look at that.

**Comment by batzen** [comment] 2019-12-21 19:30
This was fixed with dc04abd7287503bce1ff405a3dbe704847b9c7f5 and will be part of Snoop 3.0

**Closed by batzen** 2019-12-21 19:30 UTC
Labels: bug
